const sampleTrailer = "https://www.w3schools.com/html/mov_bbb.mp4"; // Tráiler genérico temporal

const MOVIES = [
  {
    id: "the-karate-kid-2",
    title: "El Karate Kid 2",
    year: 2018,
    duration: "1h 56min",
    rating: "PG",
    genres: ["Animación", "Aventura"],
    description: "",
    trailerUrl: sampleTrailer,
    image: "jokes/the-karate-kid-2.jpg",
    movie: ""
  },
  {
    id: "incredibulls-3",
    title: "Los Incredibulls 3",
    year: 2023,
    duration: "2h 20min 05s",
    rating: "PG",
    genres: ["Animación", "Acción", "Aventura", "Superhéroes"],
    description: "",
    image: "jokes/incredibulls-3.jpg",
    trailerUrl: "trailers/",
    movie: ""
  },
  {
    id: "meowana",
    title: "Meowana",
    year: 2023,
    duration: "2h 20min 05s",
    rating: "PG",
    genres: ["Animación", "Acción", "Aventura", "Superhéroes"],
    description: "",
    image: "jokes/meowana.jpg",
    trailerUrl: "trailers/",
    movie: ""
  },
  {
    id: "inside-snout2",
    title: "Salvajemente 2",
    year: 2023,
    year: 2024,
    duration: "1h 36m",
    rating: "PG-13",
    calidad: "360p",
    genres: ["Infantil","Comedia","Animación"],
    description:"Ahora que es adolescente, Riley experimenta nuevos sentimientos como Ansiedad y Envidia, que se imponen a los viejos mientras ella duda sobre si abandonar a sus antiguas amigas por otras de la escuela secundaria.",
    trailerUrl: sampleTrailer,
    image: "jokes/inside-snout2.jpg",
    post: "posters/inside-out2.webp",
    movie: "https://drive.google.com/file/d/19t0x3ixt8Xbf9ZV9dqhqdGWZevUsnt-K/preview"
  },
  {
    id: "fast_and_the_fragile_the_final_lap",
    title: "Rapidos y Frágiles - La Vuleta Final",
    year: 2023,
    duration: "2h 20min 05s",
    rating: "PG",
    genres: ["Animación", "Acción", "Aventura", "Superhéroes"],
    description: "",
    image: "jokes/fast_and_the_fragile_the_final_lap.jpg",
    trailerUrl: "trailers/across-the-spiderverse.mp4",
    movie: ""
  },
  {
    id: "inside-vice2",
    title: "Vicio Intenso 2",
    year: 2024,
    duration: "1h 36m",
    rating: "PG-13",
    calidad: "360p",
    genres: ["Infantil","Comedia","Animación"],
    description:"Ahora que es adolescente, Riley experimenta nuevos sentimientos como Ansiedad y Envidia, que se imponen a los viejos mientras ella duda sobre si abandonar a sus antiguas amigas por otras de la escuela secundaria.",
    trailerUrl: sampleTrailer,
    image: "jokes/vicio-intenso2.jpg",
    post: "posters/inside-out2.webp",
    movie: "https://drive.google.com/file/d/19t0x3ixt8Xbf9ZV9dqhqdGWZevUsnt-K/preview"
  },
  {
    id: "faiv-naigs-at-freddys2",
    title: "Faiv Naigs At Freddy's 2: Próximamente",
    year: 2026,
    duration: "1h 45min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Ha pasado un año desde la pesadilla sobrenatural en la pizzería Freddy Fazbear. La historia de lo que ocurrió allí se ha convertido en leyenda local, dando pie al primer “Fazfest”. Mike y Vanessa han mantenido en secreto la verdad a Abby, la hermana de 11 años de Mike. Pero cuando Abby decide reencontrarse con Freddy, Bonnie, Chica y Foxy, desata una serie de eventos aterradores que revelarán oscuros secretos sobre el origen de Freddy’s, desvelando un horror oculto por décadas.",
    trailerUrl: "trailers/five-nights-at-freddys2.mp4",
    image: "https://m.media-amazon.com/images/M/MV5BZmQ3NmIxNTgtYjFiNS00NzliLWI0YzAtZDkxY2E0YWIxZDEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    post: "jokes/faiv-naigs-at-freddys2.png",
    movie: ""
  },
  {
    id: "futbolito",
    title: "futbolito",
    year: 2026,
    duration: "1h 45min",
    rating: "PG-13",
    genres: [""],
    description:"",
    trailerUrl: "trailers/",
    image: "jokes/futbolito.jpg",
    post: "jokes/.png",
    movie: ""
  },
  {
    id: "la-desnutricion-del-87",
    title: "La Desnutrición del 87💀",
    year: 2026,
    duration: "1h 45min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Ha pasado un año desde la pesadilla sobrenatural en la pizzería Freddy Fazbear. La historia de lo que ocurrió allí se ha convertido en leyenda local, dando pie al primer “Fazfest”. Mike y Vanessa han mantenido en secreto la verdad a Abby, la hermana de 11 años de Mike. Pero cuando Abby decide reencontrarse con Freddy, Bonnie, Chica y Foxy, desata una serie de eventos aterradores que revelarán oscuros secretos sobre el origen de Freddy’s, desvelando un horror oculto por décadas.",
    trailerUrl: "trailers/five-nights-at-freddys2.mp4",
    image: "jokes/la-desnutricion-del-87.jpg",
    post: "jokes/",
    movie: ""
  },
  {
    id: "la-cariñosa-del-87",
    title: "La Cariñosa del 87",
    year: 20,
    duration: "1h ",
    rating: "PG-13",
    genres: [""],
    description:"",
    trailerUrl: "trailers/",
    image: "jokes/la-cariñosa-del-87.jpg",
    post: "jokes/",
    movie: ""
  },
  {
    id: "cloudy-with-achance-of-awa",
    title: "Lluvia de Awa",
    year: 20,
    duration: "1h ",
    rating: "PG-13",
    genres: [""],
    description:"",
    trailerUrl: "trailers/",
    image: "jokes/cloudy-with-achance-of-awa.webp",
    post: "jokes/",
    movie: ""
  },
  {
    id: "naruto-live-action",
    title: "Naruto :Live Action",
    year: 20,
    duration: "1h ",
    rating: "PG-13",
    genres: [""],
    description:"",
    trailerUrl: "trailers/",
    image: "jokes/naruto-live-action.jpg",
    post: "jokes/",
    movie: ""
  },
  {
    id: "pvz-live-action",
    title: "PvZ :Live Action",
    year: 20,
    duration: "1h ",
    rating: "PG-13",
    genres: [""],
    description:"",
    trailerUrl: "trailers/",
    image: "jokes/pvz-live-action.jpg",
    post: "jokes/",
    movie: ""
  },
  {
    id: "ratatouille-live-action",
    title: "Ratatouille :Live Action",
    year: 20,
    duration: "1h ",
    rating: "PG-13",
    genres: [""],
    description:"",
    trailerUrl: "trailers/",
    image: "jokes/ratatouille-live-action.jpg",
    post: "jokes/",
    movie: ""
  },
  {
    id: "women-tale",
    title: "El Espanta Viejas",
    year: 2004,
    duration: "1h 30m",
    rating: "A",
    calidad: "360p",
    genres: ["Infantil","Aventura","Animación"],
    description:"El hijo de un tiburón mafioso muere cuando le cae un ancla encima. Un pez con mucho descaro y sueños de grandeza se encontraba en la escena del crimen y, para darse importancia, se atribuye la muerte. Sin duda, un grave error.",
    trailerUrl: sampleTrailer,
    image: "jokes/espanta-viejas.png",
    post: "posters/shark-tale.webp",
    movie: "https://drive.google.com/file/d/1DVb8BQ_YxwUtDA_HBRh0PK2Ez16AB7S5/preview"
},
  {
    id: "Secret-of-the-Wings-2-Beyond-the-Glow",
    title: "TinkerBell 7: El Secreto de las Alas 2: Más Allá del Resplandor",
    year: 2012,
    duration: "1h 15min",
    rating: "PG-13",
    genres: ["Comedia", "Acción","Animación"],
    description:"El Secreto de las Alas 2: Más Allá del Resplandor (2025) cautiva al público con un mágico regreso a Pixie Hollow, donde Campanilla y sus amigas hadas se embarcan en una nueva aventura que combina imágenes impresionantes, momentos emotivos y emocionantes descubrimientos. Esta secuela profundiza el vínculo entre Tink y Periwinkle, a la vez que presenta nuevos reinos y desafíos que celebran la unidad y la maravilla.",
    trailerUrl: sampleTrailer,
    image: "jokes/Secret-of-the-Wings-2-Beyond-the-Glow.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/1ca81c90-6871-47be-b6f1-3057b17e48e5/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1FbnSkyTL26eRGxc-PZGHgQLz7Kqpa0GB/preview"
  }
];

// (Opcional) Exponerlo globalmente
window.MOVIES = MOVIES;
